### ISSUE TITLE
Access to the game from the paper

### ISSUE THREAD

**Issue by eracah** [rach0012/humanRL_prior_games#2]
Hi,
Thank you for sharing your code! I am able to get the ["simple platformer game"](https://raw.githubusercontent.com/rach0012/humanRL_prior_games/master/screens.png) from the motivating example to work with a gym wrapper using [this code](https://github.com/rach0012/humanRL_gym_ple), but I can't seem to find the main game from the paper: [the one with the pink blobs and the key](https://i.imgur.com/30O9ohe.jpg).

Do you know where/how I can get access to that one (not to play myself, but to run with a gym wrapper)?

Thank you,
Evan

**Comment by rachit-dubey** [comment]
Hi,

The main games from the paper on which we ran the human studies are HTML5 games. We created those games because we could easily collect human data via online web browsers. Unfortunately, there is no straightforward way of training RL agents on an HTML5 game (we tried a lot but due to low FPS, the RL agents would never train in a reasonable time). To solve that, we created the pygame environments shared in this repo to train the RL agents and compare their performance with humans. 

You can of course access the front end of those HTML5 games to play them yourself here - https://rach0012.github.io/humanRL_website/ but as of now we don't have a simple way to train RL agents on those games.

**Comment by eracah** [comment]
Ok thank you, Rachit, for the quick response! And the HTML game has more modes, like "hard mode" and "changed gravity direction". I assume those are not available in the pygames game?
Thanks,
Evan

**Comment by rachit-dubey** [comment]
No, they are not. However, it should be very easy to train on changed gravity direction - simply send a rotated image to the RL agent (you can do that using the ple_gym wrapper)
